spring.application.name=time-off-request

# We are going to use JDBC to control our database (H2)

# Enable H2 console
spring.h2.console.enabled: true
spring.h2.console.path=/h2-console

# H2 Configuration
spring.datasource.url=jdbc:h2:mem:assessmentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
